# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0002_auto_20161024_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='serie_text',
        ),
        migrations.AddField(
            model_name='serie',
            name='serie_identifiant',
            field=models.IntegerField(default=0),
        ),
    ]
