# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0003_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(default=0),
        ),
    ]
