# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0004_season_season_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='serie',
        ),
        migrations.AddField(
            model_name='serie',
            name='serie_json',
            field=models.CharField(default='{}', max_length=200),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
