# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0004_saison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saison',
            name='serie',
        ),
        migrations.AddField(
            model_name='serie',
            name='serie_photo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Saison',
        ),
    ]
