# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0004_season_season_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_text', models.CharField(default='Noname', max_length=200)),
                ('episode_number', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webseries.Season')),
            ],
        ),
    ]
