# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0005_auto_20161025_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie_photo',
            field=models.CharField(default='https://image.tmdb.org/t/p/w500//wQoosZYg9FqPrmI4zeCLRdEbqAB.jpg', max_length=200),
        ),
    ]
