# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0005_auto_20161111_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie_json',
            field=models.CharField(default='{}', max_length=200000),
        ),
    ]
