# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0008_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pub_date',
        ),
    ]
