# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0009_remove_account_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_identifiant',
        ),
        migrations.AddField(
            model_name='season',
            name='season_text',
            field=models.CharField(default='Noname', max_length=200),
        ),
    ]
