# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0010_auto_20161026_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_text', models.CharField(default='Noname', max_length=200)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webseries.Serie')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='season_identifiant',
            field=models.IntegerField(default=0),
        ),
    ]
