# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0011_auto_20161030_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_identifiant',
            field=models.IntegerField(default=0),
        ),
    ]
