# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0012_episode_episode_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='webseries.Season'),
        ),
    ]
