# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0012_episode_episode_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
