# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0013_auto_20161031_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default='Noname', on_delete=django.db.models.deletion.CASCADE, to='webseries.Season'),
        ),
    ]
