# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0015_auto_20161031_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season_identifiant',
            new_name='season_number',
        ),
    ]
